AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  chat-telegram

Globals:
  Function:
    Timeout: 10
    MemorySize: 128
    Handler: app.lambda_handler
    Runtime: python3.9
    Tracing: Active

  Api:
    TracingEnabled: true
Parameters:
    ConnectInstanceId:
      Type: String
      Description: The identifier of the Amazon Connect instance. You can find the instanceId in the ARN of the instance.
      Default: 77xxxx71-xxxx-xxxx-xxxx-4d5xxxxd2b6
    ContactFlowId:
      Type: String
      Description: The identifier of the flow. Under the ARN (Amazon Resource Number), copy everything after contact-flow/.
      Default: ddxxxxec-xxxx-xxxx-xxxx-7594xxxx6aea
    TelegramToken:
      Type: String
      Description: Telegram bot token to access Telegram API
      Default: 5xxxxxx:AAxxxxxxxxxxxxxxxxx



Resources:
  ContactChatTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: ChatTeleSessionMapping
      AttributeDefinitions:
        - 
          AttributeName: "ContactId"
          AttributeType: "S"
        - 
          AttributeName: "ChatId"
          AttributeType: "S"         
      KeySchema: 
        - 
          AttributeName: "ContactId"
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      GlobalSecondaryIndexes:
        - 
          IndexName: ChatId-index
          KeySchema:
            - 
              AttributeName: "ChatId"
              KeyType: "HASH"
          Projection: 
            NonKeyAttributes: 
              - "ConnectionToken"
            ProjectionType: "INCLUDE"
          ProvisionedThroughput: 
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"

  SnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: connect-chat-streaming

  InboundFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: inbound/
      Environment:
        Variables:
          INSTANCE_ID: !Ref ConnectInstanceId
          CONTACT_FLOW_ID: !Ref ContactFlowId
          STREAMING_SNS_ARN: !Ref SnsTopic
          TABLE_NAME: !Ref ContactChatTable
      Events:
        InboundApi:
          Type: Api
          Properties:
            Path: /inbound
            Method: post
      Policies:
        - AWSLambdaExecute
        - AmazonDynamoDBFullAccess
        - AmazonConnect_FullAccess

  OutboundFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: outbound/
      Environment:
        Variables:
          TELEGRAM_TOKEN: !Ref TelegramToken
          TABLE_NAME: !Ref ContactChatTable
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref SnsTopic
            FilterPolicy:
              Type:
                - "MESSAGE"
              ParticipantRole:
                - "AGENT"
      Policies:
        - AWSLambdaExecute
        - AmazonDynamoDBFullAccess


  DeleteConnectionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: delete_connection/
      Environment:
        Variables:
          TABLE_NAME: !Ref ContactChatTable
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref SnsTopic
            FilterPolicy:
              Type:
                - "EVENT"
              ParticipantRole:
                - "AGENT"
              ContentType:
                - "application/vnd.amazonaws.connect.event.participant.left"
      Policies:
        - AWSLambdaExecute
        - AmazonDynamoDBFullAccess


  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Join:
        - ''
        - - ApplicationInsights-SAM-
          - Ref: AWS::StackName
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Fn::Join:
        - ''
        - - ApplicationInsights-SAM-
          - Ref: AWS::StackName
      AutoConfigurationEnabled: 'true'
    DependsOn: ApplicationResourceGroup

Outputs:
  InboundWebhookApi:
    Description: "API Gateway endpoint URL for telegram bot to set webhook"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/inbound/"

